version: '3.9'

networks:
  dev:
    driver: bridge

services:

  api:
    container_name: auth_api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - Datasource=Host=db;Database=auth_db;Username=postgres;Password=admin;Port=5432;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - dev

volumes:
  db_data: 
